image: gradle:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - "export GRADLE_USER_HOME=`pwd`/.gradle"

build:
  script:
    - "./gradlew --build-cache build"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "*/build"
      - "*/.gradle"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
