name: "build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Java"
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
      - name: "Cache Gradle"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-
      - name: "Build"
        run: ./gradlew build --stacktrace
      - name: "Archive JARs"
        uses: actions/upload-artifact@v2
        with:
          name: "jars"
          path: |
            build/libs/*.jar
